version: '3.8'

services:
  airflow:
    build:
      context: .                # Direktori tempat Dockerfile.airflow berada
      dockerfile: Dockerfile.airflow
    image: custom-airflow:latest
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - .:/opt/airflow
      - ./mlruns:/opt/airflow/mlruns
      - ./model:/opt/airflow/model
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname Hajid --lastname Ramadhan --role Admin --email hajid@example.com --password admin &&
               airflow webserver & airflow scheduler"
